[cosmic-ray]
module-path = ".venv/Lib/site-packages/pandas/io/parsers"
test-command = "pytest tests/io/parser/test_textreader.py"
timeout = 30

[cosmic-ray.distributor]
name = "local"

[cosmic-ray.distributor.local]
